// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOYSXm2U7m2lUurp9cgnwf0gDJvpzZf4c',
    appId: '1:520567909010:web:201c65ea9d32950c4a544b',
    messagingSenderId: '520567909010',
    projectId: 'event-planner-app-803c2',
    authDomain: 'event-planner-app-803c2.firebaseapp.com',
    storageBucket: 'event-planner-app-803c2.firebasestorage.app',
    measurementId: 'G-6J8HHSVS2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98RrnZOUofFtSf4YpHedrEVU1Sc9bkqo',
    appId: '1:520567909010:android:edca3eb65ca2ee9a4a544b',
    messagingSenderId: '520567909010',
    projectId: 'event-planner-app-803c2',
    storageBucket: 'event-planner-app-803c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHCJOFA1hAuliLfhQGQ4cfW5PeOFbAy_s',
    appId: '1:520567909010:ios:ca527f82d7c7d0f14a544b',
    messagingSenderId: '520567909010',
    projectId: 'event-planner-app-803c2',
    storageBucket: 'event-planner-app-803c2.firebasestorage.app',
    iosBundleId: 'com.example.eventPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHCJOFA1hAuliLfhQGQ4cfW5PeOFbAy_s',
    appId: '1:520567909010:ios:ca527f82d7c7d0f14a544b',
    messagingSenderId: '520567909010',
    projectId: 'event-planner-app-803c2',
    storageBucket: 'event-planner-app-803c2.firebasestorage.app',
    iosBundleId: 'com.example.eventPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOYSXm2U7m2lUurp9cgnwf0gDJvpzZf4c',
    appId: '1:520567909010:web:fbd9e0990994fc604a544b',
    messagingSenderId: '520567909010',
    projectId: 'event-planner-app-803c2',
    authDomain: 'event-planner-app-803c2.firebaseapp.com',
    storageBucket: 'event-planner-app-803c2.firebasestorage.app',
    measurementId: 'G-58VMY97T1D',
  );
}
